# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 14:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_code', models.CharField(help_text='The code given to a user', max_length=255)),
                ('time_duration', models.DurationField(help_text='The duration time to answer the question')),
                ('answer', models.CharField(help_text='The answer. Either from a dropdown or choice', max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Timestamp of the answer')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(help_text='Added your Choice text here.', max_length=255)),
                ('right_answer', models.BooleanField(default=False, help_text='Is this a right answer?')),
            ],
        ),
        migrations.CreateModel(
            name='Dropdown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dropdown_text', models.CharField(help_text='Added your Dropdown text here.', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(help_text='Added your Question text here.')),
                ('is_it_singlechoice', models.BooleanField(default=False, help_text='Is there two possiblity choice e.g. True or False?')),
                ('is_it_multichoices', models.BooleanField(default=False, help_text='Is there multiple right choices ?')),
                ('is_it_dropdown', models.BooleanField(default=False, help_text='Is it a dropdown?')),
            ],
        ),
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of Schema', max_length=32)),
                ('body', models.TextField(help_text='Insert the Schema here :)')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='schema',
            field=models.ForeignKey(help_text='Choose a Schema', on_delete=django.db.models.deletion.CASCADE, to='polls.Schema'),
        ),
        migrations.AddField(
            model_name='dropdown',
            name='question',
            field=models.ForeignKey(help_text='Choose a question for this answer', on_delete=django.db.models.deletion.CASCADE, to='polls.Question'),
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(help_text='Choose a question for this answer', on_delete=django.db.models.deletion.CASCADE, to='polls.Question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(help_text='the question answered', on_delete=django.db.models.deletion.CASCADE, to='polls.Question'),
        ),
    ]
