# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.TextField(help_text='Added your Choice text here.'),
        ),
        migrations.AlterField(
            model_name='dropdown',
            name='dropdown_text',
            field=models.TextField(help_text='Added your Dropdown text here.'),
        ),
        migrations.AlterField(
            model_name='schema',
            name='name',
            field=models.TextField(help_text='Name of Schema'),
        ),
    ]
