# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20171123_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schema',
            name='name',
            field=models.CharField(help_text='Name of Schema', max_length=255),
        ),
    ]
