# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 15:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20171123_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='question_type',
            field=models.CharField(default=django.utils.timezone.now, help_text='The Question type', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answer',
            name='tech_type',
            field=models.CharField(default=django.utils.timezone.now, help_text='Technique Type if any', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='choice',
            name='technique',
            field=models.CharField(choices=[('DOMINO', 'Domino'), ('SELECTOR', 'Selector'), ('SOURCER', 'Sourcer'), ('READER', 'Reader'), ('AVMLM', 'AVM-LM'), ('AVMR', 'AVM-R'), ('AVMD', 'AVM-D')], default='DOMINO', max_length=255),
        ),
        migrations.AddField(
            model_name='dropdown',
            name='technique',
            field=models.CharField(choices=[('DOMINO', 'Domino'), ('SELECTOR', 'Selector'), ('SOURCER', 'Sourcer'), ('READER', 'Reader'), ('AVMLM', 'AVM-LM'), ('AVMR', 'AVM-R'), ('AVMD', 'AVM-D')], default='DOMINO', max_length=255),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('BACKGROUND', 'Background'), ('ALL', 'All'), ('ASSERT', 'Assertion')], default='ALL', max_length=255),
        ),
    ]
