# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 16:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20171123_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='technique',
            field=models.CharField(choices=[('DOMINO', 'Domino'), ('SELECTOR', 'Selector'), ('SOURCER', 'Sourcer'), ('READER', 'Reader'), ('COLNAMEr', 'ColumnNamer'), ('AVMLM', 'AVM-LM'), ('AVMR', 'AVM-R'), ('AVMD', 'AVM-D')], default='DOMINO', max_length=255),
        ),
        migrations.AlterField(
            model_name='dropdown',
            name='technique',
            field=models.CharField(choices=[('DOMINO', 'Domino'), ('SELECTOR', 'Selector'), ('SOURCER', 'Sourcer'), ('READER', 'Reader'), ('COLNAMEr', 'ColumnNamer'), ('AVMLM', 'AVM-LM'), ('AVMR', 'AVM-R'), ('AVMD', 'AVM-D')], default='DOMINO', max_length=255),
        ),
        migrations.AlterField(
            model_name='question',
            name='schema',
            field=models.ForeignKey(help_text='Choose a Schema', null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Schema'),
        ),
    ]
