# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20171123_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_insert_statement',
            field=models.TextField(blank=True, help_text='If there is any insert statements, added here', null=True),
        ),
    ]
