# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_question_question_insert_statement'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='is_it_right',
            field=models.BooleanField(default=False, help_text='Did the test taker get it right?'),
        ),
    ]
