# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 11:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_answer_is_it_right'),
    ]

    operations = [
        migrations.CreateModel(
            name='RandomisedAnswersOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_code', models.CharField(help_text='The code given to a user', max_length=255)),
                ('question', models.ForeignKey(help_text='List of Questins', on_delete=django.db.models.deletion.CASCADE, to='polls.Question')),
            ],
        ),
    ]
