# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_randomisedanswersorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='randomisedanswersorder',
            name='answered',
            field=models.BooleanField(default=False, help_text='is this question answered?'),
        ),
    ]
