# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_auto_20171127_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='time_duration',
            field=models.BigIntegerField(help_text='The duration time (Millisconds) to answer the question'),
        ),
    ]
