# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 17:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_auto_20171127_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dropdown',
            name='question',
            field=models.ForeignKey(help_text='Choose a question for this answer', on_delete=django.db.models.deletion.CASCADE, related_name='dropdown', to='polls.Question'),
        ),
    ]
