# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_auto_20171127_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='technique',
            field=models.CharField(blank=True, choices=[('DOMINO', 'Domino'), ('SELECTOR', 'Selector'), ('SOURCER', 'Sourcer'), ('READER', 'Reader'), ('COLNAMER', 'ColumnNamer'), ('AVMLM', 'AVM-LM'), ('AVMR', 'AVM-R'), ('AVMD', 'AVM-D')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='choice',
            name='technique',
            field=models.CharField(choices=[('DOMINO', 'Domino'), ('SELECTOR', 'Selector'), ('SOURCER', 'Sourcer'), ('READER', 'Reader'), ('COLNAMER', 'ColumnNamer'), ('AVMLM', 'AVM-LM'), ('AVMR', 'AVM-R'), ('AVMD', 'AVM-D')], default='DOMINO', max_length=255),
        ),
        migrations.AlterField(
            model_name='dropdown',
            name='technique',
            field=models.CharField(choices=[('DOMINO', 'Domino'), ('SELECTOR', 'Selector'), ('SOURCER', 'Sourcer'), ('READER', 'Reader'), ('COLNAMER', 'ColumnNamer'), ('AVMLM', 'AVM-LM'), ('AVMR', 'AVM-R'), ('AVMD', 'AVM-D')], default='DOMINO', max_length=255),
        ),
    ]
