# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 08:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_auto_20171204_1024'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchemaShowedOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_code', models.CharField(help_text='The code given to a user', max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('showed', models.BooleanField(default=False, help_text='have the schema been showed?')),
                ('schema', models.ForeignKey(help_text='Schema', on_delete=django.db.models.deletion.CASCADE, to='polls.Schema')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('BACKGROUND', 'Background'), ('ALL', 'All'), ('ASSERT', 'Assertion')], default='ASSERT', max_length=255),
        ),
    ]
