# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_auto_20171206_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='opinion_text',
            field=models.TextField(blank=True, help_text='opinion text', null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='is_it_opinion',
            field=models.BooleanField(default=False, help_text='Is it an opinion?'),
        ),
    ]
