# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-23 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_group_groupquestions_groupuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupquestions',
            name='assertion_type',
            field=models.CharField(choices=[('VPK', 'Violate PK'), ('VNN', 'Violate NN'), ('VFK', 'Violate FK'), ('VUQ', 'Violate UQ'), ('VCC', 'Violate CC'), ('VPK', 'Satisfy PK'), ('VNN', 'Satisfy NN'), ('VFK', 'Satisfy FK'), ('VUQ', 'Satisfy UQ'), ('VCC', 'Satisfy CC')], default='VPK', max_length=255),
        ),
        migrations.AddField(
            model_name='question',
            name='assertion_type',
            field=models.CharField(choices=[('VPK', 'Violate PK'), ('VNN', 'Violate NN'), ('VFK', 'Violate FK'), ('VUQ', 'Violate UQ'), ('VCC', 'Violate CC'), ('VPK', 'Satisfy PK'), ('VNN', 'Satisfy NN'), ('VFK', 'Satisfy FK'), ('VUQ', 'Satisfy UQ'), ('VCC', 'Satisfy CC')], default='VPK', max_length=255),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('BACKGROUND', 'Background'), ('ALL', 'All'), ('ASSERT', 'Assertion'), ('practice', 'Practice'), ('EXIT', 'Exit')], default='ASSERT', max_length=255),
        ),
    ]
