# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-04-25 11:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pcode', models.CharField(help_text='Participant Code', max_length=255)),
                ('duration', models.BigIntegerField(help_text='Answering Duration (Millisconds)')),
                ('answer', models.CharField(help_text='The answer', max_length=255)),
                ('score', models.BooleanField(default=False, help_text='Right or Wrong')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Timestamp of the answer')),
                ('opinion', models.TextField(blank=True, help_text='Participant Opinion', null=True)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of Group', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Participants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pcode', models.CharField(help_text='Participant Code - Manual Generation or Automated', max_length=255)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controlled.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of Program (e.g., Class or Schema)', max_length=255)),
                ('code', models.TextField(blank=True, help_text='Program Code', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pcode', models.CharField(help_text='Participant Code', max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('showed', models.BooleanField(default=False, help_text='have the schema been showed?')),
                ('program', models.ForeignKey(help_text='Schema', on_delete=django.db.models.deletion.CASCADE, to='controlled.Program')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(blank=True, help_text='Code Associated with the Question', null=True)),
                ('singlechoice', models.BooleanField(default=False, help_text='One choice e.g. True or False?')),
                ('multichoices', models.BooleanField(default=False, help_text='multiple choices?')),
                ('opinion', models.BooleanField(default=False, help_text='Requiring Opinion?')),
                ('program', models.ForeignKey(blank=True, help_text='Choose a Program', null=True, on_delete=django.db.models.deletion.CASCADE, to='controlled.Program')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='Question Category')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='Unique Name for your Question')),
                ('question_text', models.TextField(help_text='Question text.')),
            ],
        ),
        migrations.CreateModel(
            name='RandomisedAnswersOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pcode', models.CharField(help_text='Participant Code', max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('answered', models.BooleanField(default=False, help_text='is this question answered?')),
                ('question', models.ForeignKey(help_text='List of Questins', on_delete=django.db.models.deletion.CASCADE, to='controlled.Question')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_case_id', models.CharField(help_text='Test Case ID', max_length=255)),
                ('code', models.TextField(blank=True, help_text='Test Case Code', null=True)),
                ('assertion', models.CharField(choices=[('T', 'TURE'), ('F', 'FALSE')], default='T', help_text='It Expects what? True or False. \n    Can be changed in models.py', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TestSuite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_suite_id', models.CharField(help_text='Test Suite ID', max_length=255)),
                ('code', models.TextField(blank=True, help_text='Test Suite Code', null=True)),
                ('automated', models.BooleanField(default=True, help_text='Is it a dropdown?')),
                ('auto_method', models.CharField(choices=[('MAN', 'Manual'), ('RND', 'Random'), ('AVMD', 'AVM-D'), ('AVMR', 'AVM-R'), ('DOMINOR', 'Domino-R'), ('DOMINOD', 'Domino-D')], default='DOMINOR', max_length=255)),
                ('program', models.ForeignKey(help_text='Choose a Program', on_delete=django.db.models.deletion.CASCADE, to='controlled.Program')),
            ],
        ),
        migrations.AddField(
            model_name='testcase',
            name='test_suite',
            field=models.ForeignKey(help_text='Choose a Test Suite', on_delete=django.db.models.deletion.CASCADE, to='controlled.TestSuite'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_category',
            field=models.ForeignKey(blank=True, help_text='Choose a Question Category', null=True, on_delete=django.db.models.deletion.CASCADE, to='controlled.QuestionCategory'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_text',
            field=models.ForeignKey(blank=True, help_text='Choose a Question', null=True, on_delete=django.db.models.deletion.CASCADE, to='controlled.QuestionText'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(help_text='Question Answered', on_delete=django.db.models.deletion.CASCADE, to='controlled.Question'),
        ),
    ]
