# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-04-25 11:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controlled', '0002_auto_20190425_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='code',
        ),
        migrations.AddField(
            model_name='question',
            name='test_suite',
            field=models.ForeignKey(default=0, help_text='Choose a Test Suite', on_delete=django.db.models.deletion.CASCADE, to='controlled.TestSuite'),
            preserve_default=False,
        ),
    ]
