# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-04-25 16:03
from __future__ import unicode_literals

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('controlled', '0003_auto_20190425_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexPageContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Study Title', max_length=255)),
                ('text', markdownx.models.MarkdownxField(blank=True, help_text='Markdown Text', null=True)),
                ('default', models.BooleanField(default=False, help_text='Is this the default content?')),
            ],
        ),
        migrations.AlterField(
            model_name='testsuite',
            name='automated',
            field=models.BooleanField(default=True, help_text='Automated = TRUE or Manual = FALSE ? Default is TRUE'),
        ),
    ]
