# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-04-30 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlled', '0006_auto_20190430_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questioncategory',
            name='name',
            field=models.CharField(help_text='Question Category', max_length=255),
        ),
        migrations.AlterField(
            model_name='questiontext',
            name='name',
            field=models.CharField(help_text='Unique Name for your Question', max_length=255),
        ),
    ]
