# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-04-30 12:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controlled', '0007_auto_20190430_1050'),
    ]

    operations = [
        migrations.CreateModel(
            name='MutatedProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(blank=True, help_text='Program Code', null=True)),
                ('program', models.ForeignKey(help_text='Choose a Program', on_delete=django.db.models.deletion.CASCADE, to='controlled.Program')),
            ],
        ),
    ]
