# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-05-07 15:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controlled', '0011_auto_20190507_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='DropdownOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(help_text='Added your Dropdown text here.', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DropdownQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(help_text='Added your Dropdown text here.', max_length=255)),
                ('question', models.ForeignKey(help_text='Choose a question.', on_delete=django.db.models.deletion.CASCADE, related_name='question_dropdown', to='controlled.Question')),
            ],
        ),
        migrations.RemoveField(
            model_name='dropdown',
            name='question',
        ),
        migrations.DeleteModel(
            name='Dropdown',
        ),
        migrations.AddField(
            model_name='dropdownoption',
            name='dropdown_question',
            field=models.ForeignKey(help_text='The dropdown questions', on_delete=django.db.models.deletion.CASCADE, to='controlled.DropdownQuestion'),
        ),
    ]
