# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-05-08 14:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controlled', '0012_auto_20190507_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dropdownquestion',
            name='question',
        ),
        migrations.RemoveField(
            model_name='dropdownoption',
            name='dropdown_question',
        ),
        migrations.AddField(
            model_name='dropdownoption',
            name='question',
            field=models.ForeignKey(default=0, help_text='Choose a question.', on_delete=django.db.models.deletion.CASCADE, related_name='question_dropdown', to='controlled.Question'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='DropdownQuestion',
        ),
    ]
