# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-05-08 16:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controlled', '0013_auto_20190508_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Select Group', null=True, on_delete=django.db.models.deletion.CASCADE, to='controlled.Group'),
        ),
        migrations.AlterField(
            model_name='programorder',
            name='program',
            field=models.ForeignKey(help_text='Program', on_delete=django.db.models.deletion.CASCADE, to='controlled.Program'),
        ),
        migrations.AlterField(
            model_name='programorder',
            name='showed',
            field=models.BooleanField(default=False, help_text='have the program been showed?'),
        ),
    ]
