# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-05-10 16:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controlled', '0014_auto_20190508_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnsweredTestCases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pcode', models.CharField(help_text='Participant Code', max_length=255)),
                ('duration', models.BigIntegerField(help_text='Answering Duration (Millisconds)')),
                ('answer', models.CharField(help_text='The answer', max_length=255)),
                ('score', models.IntegerField(default=0, help_text='Score')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Timestamp of the answer')),
                ('testCase', models.ForeignKey(help_text='TestCase Answered', on_delete=django.db.models.deletion.CASCADE, to='controlled.TestCase')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
