# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-05-14 12:12
from __future__ import unicode_literals

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('controlled', '0016_remove_answeredtestcases_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexpagecontent',
            name='consent',
            field=markdownx.models.MarkdownxField(blank=True, help_text='Consent Markdown Text', null=True),
        ),
    ]
